# Generated by Django 5.1 on 2025-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department where incident occurred",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="facility",
            field=models.CharField(
                blank=True,
                help_text="Location / Facility name where incident occurred",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="persons_involved_details",
            field=models.TextField(
                blank=True,
                help_text="Details of persons involved (names, roles, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="site",
            field=models.CharField(
                blank=True,
                help_text="Specific site location",
                max_length=100,
                null=True,
            ),
        ),
    ]
